[build]
  publish = "_site"                # Dossier de sortie généré par Eleventy
  command = "eleventy"             # Commande pour générer le site
  node_version = "20.10.0"

[dev]
  command = "eleventy --serve"     # Commande pour lancer le serveur de développement

[functions]
  directory = "netlify/functions"  # Répertoire pour les fonctions serverless

# Redirection générale pour ajouter une barre oblique aux URLs (hors fichiers statiques)
[[redirects]]
  from = "/:splat"
  to = "/:splat/"
  status = 301
  force = true

# Exceptions pour les fichiers spécifiques (exclure des redirections générales)
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Redirection pour les fonctions API
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
  force = true

# Gestion de la page 404 personnalisée
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Configuration des en-têtes HTTP
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.(jpg|jpeg|png|gif|svg|webp)"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
